// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsofabehtfixglhjfvvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhzb2ZhYmVodGZpeGdsaGpmdnZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzQ5NjgsImV4cCI6MjA3Mzc1MDk2OH0.Mw0sUbzKtfWR8m_P0SQWIXHIhhF6dl_5YUdWeTlMaXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});